gui:
  theme:
    activeBorderColor:
      - "#a7c080"
      - bold
    inactiveBorderColor:
      - "#414b50"
    optionsTextColor:
      - "#dbbc7f"
    selectedLineBgColor:
      - "#2e383c"
    cherryPickedCommitBgColor:
      - "#414b50"
    cherryPickedCommitFgColor:
      - "#a7c080"
    unstagedChangesColor:
      - "#e67e80"
    defaultFgColor:
      - "#d3c6aa"
    searchingActiveBorderColor:
      - "#dbbc7f"

  authorColors:
    "*": "#d699b6"
