gui:
  theme:
    activeBorderColor:
      - "#fe8019"
      - bold
    inactiveBorderColor:
      - "#3c3836"
    optionsTextColor:
      - "#fabd2f"
    selectedLineBgColor:
      - "#3c3836"
    cherryPickedCommitBgColor:
      - "#504945"
    cherryPickedCommitFgColor:
      - "#b8bb26"
    unstagedChangesColor:
      - "#fb4934"
    defaultFgColor:
      - "#ebdbb2"
    searchingActiveBorderColor:
      - "#fabd2f"

  authorColors:
    "*": "#d3869b"
