# ~/.config/starship.toml

# Inserts a blank line between shell prompts
add_newline = true

# Change the default prompt format
format = """
[](#cc241d)
$os
$username
[](bg:#d65d0e fg:#cc241d)
$directory
[](fg:#d65d0e bg:#d79921)
$git_branch
$git_status
[](fg:#d79921 bg:#458588)
$c
$rust
$golang
$nodejs
$php
$java
[](fg:#458588 bg:#689d6a)
$docker_context
[](fg:#689d6a bg:#b16286)
$time
[ ](fg:#b16286)
"""

# Change the prompt characters on success and error
[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

# Shows the username
[username]
show_always = true
style_user = "bg:#cc241d fg:#ebdbb2"
style_root = "bg:#cc241d fg:#ebdbb2"
format = "[$user]($style)"

[os]
style = "bg:#cc241d fg:#ebdbb2"
disabled = false # Disabled by default

[directory]
style = "bg:#d65d0e fg:#ebdbb2"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:#d79921 fg:#1d2021"
format = "[ $symbol $branch ]($style)"

[git_status]
style = "bg:#d79921 fg:#1d2021"
format = "[$all_status$ahead_behind ]($style)"

[nodejs]
symbol = ""
style = "bg:#458588 fg:#ebdbb2"
format = "[ $symbol ($version) ]($style)"

[c]
symbol = ""
style = "bg:#458588 fg:#ebdbb2"
format = "[ $symbol ($version) ]($style)"

[rust]
symbol = ""
style = "bg:#458588 fg:#ebdbb2"
format = "[ $symbol ($version) ]($style)"

[golang]
symbol = ""
style = "bg:#458588 fg:#ebdbb2"
format = "[ $symbol ($version) ]($style)"

[php]
symbol = ""
style = "bg:#458588 fg:#ebdbb2"
format = "[ $symbol ($version) ]($style)"

[java]
symbol = ""
style = "bg:#458588 fg:#ebdbb2"
format = "[ $symbol ($version) ]($style)"

[docker_context]
symbol = ""
style = "bg:#689d6a fg:#1d2021"
format = "[ $symbol $context ]($style)"

[time]
disabled = false
time_format = "%R" # Hour:Minute format
style = "bg:#b16286 fg:#ebdbb2"
format = "[ $time ]($style)"
