# ~/.config/starship.toml

# Inserts a blank line between shell prompts
add_newline = true

# Change the default prompt format
format = """
[](#9A348E)
$os
$username
[](bg:#DA627D fg:#9A348E)
$directory
[](fg:#DA627D bg:#FCA17D)
$git_branch
$git_status
[](fg:#FCA17D bg:#86BBD8)
$c
$rust
$golang
$nodejs
$php
$java
[](fg:#86BBD8 bg:#06969A)
$docker_context
[](fg:#06969A bg:#33658A)
$time
[ ](fg:#33658A)
"""

# Change the prompt characters on success and error
[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

# Shows the username
[username]
show_always = true
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = "[$user]($style)"

[os]
style = "bg:#9A348E"
disabled = false # Disabled by default

[directory]
style = "bg:#DA627D"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:#FCA17D"
format = "[ $symbol $branch ]($style)"

[git_status]
style = "bg:#FCA17D"
format = "[$all_status$ahead_behind ]($style)"

[nodejs]
symbol = ""
style = "bg:#86BBD8"
format = "[ $symbol ($version) ]($style)"

[c]
symbol = ""
style = "bg:#86BBD8"
format = "[ $symbol ($version) ]($style)"

[rust]
symbol = ""
style = "bg:#86BBD8"
format = "[ $symbol ($version) ]($style)"

[golang]
symbol = ""
style = "bg:#86BBD8"
format = "[ $symbol ($version) ]($style)"

[php]
symbol = ""
style = "bg:#86BBD8"
format = "[ $symbol ($version) ]($style)"

[java]
symbol = ""
style = "bg:#86BBD8"
format = "[ $symbol ($version) ]($style)"

[docker_context]
symbol = ""
style = "bg:#06969A"
format = "[ $symbol $context ]($style)"

[time]
disabled = false
time_format = "%R" # Hour:Minute format
style = "bg:#33658A"
format = "[ $time ]($style)"

